### ISSUE TITLE
Missing or unknown field in csv file header. Please check your samplesheet

### ISSUE THREAD

**Issue by angelussong** [zhanyinx/clonal_evolution#1]
Hi, 

Thanks for publishing this workflow. I am trying to run it on a cohort of WES paired samples to generate pyclone input. 

However, when I assembled the input and run, I ran into this error: 
```
------------------------------------------------------
[-        ] CLO…VOLUTION:generate_ascat_gc -
[-        ] CLO…VOLUTION:generate_ascat_rt -
[-        ] CLO…LUTION:generate_ascat_loci -
[-        ] CLO…ION:generate_ascat_alleles -

[-        ] CLO…VOLUTION:generate_ascat_gc -
[-        ] CLO…VOLUTION:generate_ascat_rt -
[-        ] CLO…LUTION:generate_ascat_loci -
[-        ] CLO…ION:generate_ascat_alleles -
[-        ] CLONAL_EVOLUTION:BAM_TO_CRAM   -
[-        ] CLONAL_EVOLUTION:ASCAT         -
[-        ] CLO…EVOLUTION:generate_pyclone -
[-        ] CLONAL_EVOLUTION:pyclone       -
[-        ] CLONAL_EVOLUTION:convert2citup -
[-        ] CLONAL_EVOLUTION:citup         -
[-        ] CLONAL_EVOLUTION:timescape     -
Missing or unknown field in csv file header. Please check your samplesheet
WARN: Singularity cache directory has not been defined -- Remote image will be stored in the path: /wynton/scratch/hsong1/Pyclone/work/singularity -- Use the environment variable NXF_SINGULARITY_CACHEDIR to specify a different location
Pulling Singularity image docker://yinxiu/clonal_evolution:latest [cache /wynton/scratch/hsong1/Pyclone/work/singularity/yinxiu-clonal_evolution-latest.img]

[-        ] CLO…VOLUTION:generate_ascat_gc -
[-        ] CLO…VOLUTION:generate_ascat_rt -
[-        ] CLO…LUTION:generate_ascat_loci -
[-        ] CLO…ION:generate_ascat_alleles -
[-        ] CLONAL_EVOLUTION:BAM_TO_CRAM   -
[-        ] CLONAL_EVOLUTION:ASCAT         -
[-        ] CLO…EVOLUTION:generate_pyclone -
[-        ] CLONAL_EVOLUTION:pyclone       -
[-        ] CLONAL_EVOLUTION:convert2citup -
[-        ] CLONAL_EVOLUTION:citup         -
[-        ] CLONAL_EVOLUTION:timescape     -
Missing or unknown field in csv file header. Please check your samplesheet

```
And here is the first few rows of my input csv file: 
patient,sex,status,sample,bam,bai,maf
RESPOND_10100829,XY,1,RESPOND_10100829_T,Batch_02_23/RESPOND_10100829_T1_Malignant_sorted.bam,Batch_02_23/RESPOND_10100829_T1_Malignant_sorted.bam.bai,/pyclone/MAF/RESPOND_10100829.maf
RESPOND_10100829,XY,0,RESPOND_10100829_C,Batch_02_23/RESPOND_10100829_C1_Non-Malignant_sorted.bam,Batch_02_23/RESPOND_10100829_C1_Non-Malignant_sorted.bam.bai,/pyclone/MAF/RESPOND_10100829.maf
RESPOND_10100899,XY,1,RESPOND_10100899_T,Batch_02_23/RESPOND_10100899_T1_Malignant_sorted.bam,Batch_02_23/RESPOND_10100899_T1_Malignant_sorted.bam.bai,/pyclone/MAF/RESPOND_10100899.maf
RESPOND_10100899,XY,0,RESPOND_10100899_C,Batch_02_23/RESPOND_10100899_C1_Non-Malignant_sorted.bam,Batch_02_23/RESPOND_10100899_C1_Non-Malignant_sorted.bam.bai,/pyclone/MAF/RESPOND_10100899.maf

Thanks so much for your help!

**Comment by zhanyinx** [comment]
Hi @angelussong , you miss the cellularity column in the input file. If you do not have it, you still need it in the input file which can be left empty. In the next version, I will cope with missing cellularity column

Best
Zhan

**Comment by angelussong** [comment]
Thanks for your quick response! But I tried adding the cellularity column before the maf and added just "" in the input file. 
`patient,sex,status,sample,bam,bai,cellularity,maf
RESPOND_10100829,XY,1,RESPOND_10100829_T,Batch_02_23/RESPOND_10100829_T1_Malignant_sorted.bam,Batch_02_23/RESPOND_10100829_T1_Malignant_sorted.bam.bai,,/pyclone/MAF/RESPOND_10100829.maf
RESPOND_10100829,XY,0,RESPOND_10100829_C,Batch_02_23/RESPOND_10100829_C1_Non-Malignant_sorted.bam,Batch_02_23/RESPOND_10100829_C1_Non-Malignant_sorted.bam.bai,,/pyclone/MAF/RESPOND_10100829.maf
RESPOND_10100899,XY,1,RESPOND_10100899_T,Batch_02_23/RESPOND_10100899_T1_Malignant_sorted.bam,Batch_02_23/RESPOND_10100899_T1_Malignant_sorted.bam.bai,,/pyclone/MAF/RESPOND_10100899.maf
RESPOND_10100899,XY,0,RESPOND_10100899_C,Batch_02_23/RESPOND_10100899_C1_Non-Malignant_sorted.bam,Batch_02_23/RESPOND_10100899_C1_Non-Malignant_sorted.bam.bai,,/pyclone/MAF/RESPOND_10100899.maf`
The exact same error was observed. Neither would it run if I use "NA" instead of "" for the cellularity. 

Could you please suggest what I did wrong or how to correct it?

Thanks!

**Comment by zhanyinx** [comment]
Hi @angelussong ,

I completely missed your response.
Could you please try to add also the column "lane"?

Best
Zhan

**Comment by angelussong** [comment]
Thanks for your reply!! For "Lane" what should I input or just leave it empty?

**Comment by zhanyinx** [comment]
you can just leave it empty

**Comment by angelussong** [comment]
Thanks!! I think I'm able to get it to run but it takes too long. One
question I have is that since I'm running the locally downloaded pipeline
and the compute node for our cluster has no internet connection. Therefore
when I submit a job to run on the compute node, it's always spitting the
error "cannot connect to nextflow.io". I'm wondering if you happen to know
how to disable the "check for plugin" or "check for update" in the pipeline
so that it won't require any internet connection to run the job?

Thanks again for your help!

**Comment by zhanyinx** [comment]
Hi, it needs internet connection as it needs to download the singularity image and nextflow plugins
